### ISSUE TITLE
problem in p2ch1 Calculator code

### ISSUE THREAD

**Issue by kiFad** [geoffreyarthaud/oc-testing-java-cours#2]
Hi
There is in error in the code of digitsSet in the p2ch1 branch.
Current version:  integers.add(Integer.parseInt(numberString, i, i + 1, 10));
whilst signature of parseInt is parseInt​(String s, int radix)
So I guess the code should be something like integers.add(Integer.parseUnsignedInt(Character.toString(numberString.charAt(i)), 10));
Regards
Kirill

**Comment by geoffreyarthaud** [comment]
Hi,

This project has to be compiled with JDK 11+. As you can see on the [documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html#parseInt(java.lang.CharSequence,int,int,int)), this signature for parseInt is correct. I guess you're using a JDK 8.

Regards
Geoffrey
